name: traefik

services:
  traefik:
    # The official Traefik docker image
    image: traefik
    restart: unless-stopped
    command:
      # Tell Traefik to listen to docker
      - --providers.docker
      # Entrypoints
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      # Use Let's Encrypt to generate certificates
      - --certificatesresolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.le.acme.email=${LE_EMAIL}
      - --certificatesresolvers.le.acme.storage=/mnt/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      #- --log.level=DEBUG
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
    volumes:
      # Let's Encrypt certificates
      - letsencrypt:/mnt/letsencrypt
      # Allow Traefik to listen to Docker events
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  letsencrypt:

# Create a network named 'traefik'
networks:
  default:
    name: traefik
    external: false
